### PR TITLE
Fix (shortIdentString|identString) document

### LINKED ISSUE #937: identString didn't work as the document example
I executed `stack haddock` and saw the page of `shortIdentString` and `identString` .  
I saw this example .

```
>>> shortIdentString 3 (MemBuffer "hello")
"*hello*"
>>> shortIdentString 3 (FileBuffer "hello")
"lo"
```

```
>>> identString (MemBuffer "hello")
"*hello*"
>>> identString (FileBuffer "hello")
"hello"
```

I execute `stack ghci` and this .  
And I got the errors .
```
>>> identString (MemBuffer "hello")
<interactive>:2:14-26: error:
    • Couldn't match expected type ‘FBuffer’
                  with actual type ‘BufferId’
    • In the first argument of ‘identString’, namely ‘(MemBuffer "a")’
      In the expression: identString (MemBuffer "a")
      In an equation for ‘it’: it = identString (MemBuffer "a")

```
Is the document wrong ? :thinking:

### PR DESCRIPTION
**Pull request by aiya000**
Fix #937

### CODE REVIEW

File: yi-core/src/Yi/Buffer/Misc.hs [hunk 1]
```diff
@@ -245,12 +245,14 @@ instance HasAttributes FBuffer where
 
 -- | Gets a short identifier of a buffer. If we're given a 'MemBuffer'
 -- then just wraps the buffer name like so: @*name*@. If we're given a
--- 'FileBuffer', it drops the the number of characters specified.
+-- 'FileBuffer', it drops the number of the directory path.
```
Comment (aiya000) [inline yi-core/src/Yi/Buffer/Misc.hs]: Thanks :smile:  
I replaced to it :+1:
